# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- Demo

pool:
  vmImage: 'vs2017-win2016'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install python-docx
    pip install azure-devops
    pip install docxtpl
    pip install beautifulsoup4
    pip install pywin32
  displayName: 'Install dependencies'

- script: |
    dir $(Build.SourcesDirectory)
    python $(Build.SourcesDirectory)\src\com\kuka\App.py
    dir c:\
  displayName: 'python run'

# Command Line
# Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
- task: CmdLine@2
  inputs:
    script: 'echo Write your commands here.' 

- script: |
    pip show azure-devops > a.txt
    for /f "tokens=2* delims= " %%a in ('call findstr "Location" a.txt') do (set azure-devops=%%a)
    echo %azure-devops%
    dir .
    del a.txt
    mkdir .\\dist\\App\\azure
    xcopy /E %azure-devops%\\azure .\\dist\\App\\azure
    tree .\\dist\\App\\azure
  displayName: dos commands